apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sallowedusers
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  crd:
    spec:
      names:
        kind: K8sAllowedUsers
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sallowedusers

        violation[{"msg": msg}] {
          # Block if Pod-level runAsUser is explicitly 0
          input.review.object.spec.securityContext.runAsUser == 0
          msg := "Pod securityContext runAsUser must not be 0"
        }
        violation[{"msg": msg}] {
          # Block if Container-level runAsUser is explicitly 0
          container := input_containers[_]
          container.securityContext.runAsUser == 0
          msg := sprintf("Container <%v> securityContext runAsUser must not be 0", [container.name])
        }

        input_containers[c] {
          c := input.review.object.spec.containers[_]
        }
        input_containers[c] {
          c := input.review.object.spec.initContainers[_]
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedUsers
metadata:
  name: container-allowed-users
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - demo
