apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-password
spec:
  refreshInterval: 50s
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: db-password              # Tên K8s Secret sẽ được tạo
    creationPolicy: Owner          # ESO sở hữu Secret này
  data:
    - secretKey: password          # Key trong K8s Secret
      remoteRef:
        key: myapp/db-password     # Tên secret trên AWS Secrets Manager
        property: password         # Property trong AWS secret (nếu là JSON)
